### ISSUE TITLE
mew.org is down

### ISSUE THREAD

**Issue by christianromney** [kazu-yamamoto/mighttpd#1]

**Comment by kazu-yamamoto** [comment]
Thank you for letting me know this.
I have restarted Mighty on mew.org and the web service is now available.
I need to investigate why this happen.

**Comment by lukel97** [comment]
mew.org is down again 😬

**Comment by kazu-yamamoto** [comment]
Uhhm. I restarted mighttpd again. No cue why this happens, sigh. Thank you for noticing.

**Comment by lukel97** [comment]
I hate to be the bearer of bad news but it's down again 😆
