### ISSUE TITLE
mew.org site is down

### ISSUE THREAD

**Issue by chenrui333** [kazu-yamamoto/mighttpd#2]
👋  it looks like the site is down again.

```
$ curl -I https://www.mew.org/~kazu/proj/mighttpd/
HTTP/2 404
alt-svc: h3=":443",h3-29=":443"
date: Tue, 19 Oct 2021 05:43:21 GMT
server: Mighttpd/4.0.0
content-type: text/plain
```

- relates to https://github.com/Homebrew/homebrew-core/pull/87540

**Comment by kazu-yamamoto** [comment]
Sorry. It moved to: https://kazu-yamamoto.github.io/mighttpd2/

**Comment by chenrui333** [comment]
I see, make sense. Thanks @kazu-yamamoto!
